service: estimate-co2

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1
  # optional, in MB, default is 1024, min is 128
  memorySize: 128
  # optional, in seconds, default is 6
  timeout: 30
  # optional, default is true
  versionFunctions: false

functions:
  estimate-co2:
    handler: handler.post
    events:
      - http:
          path: /estimate-co2
          method: get
plugins:
  - serverless-python-requirements
