service: estimate-co2

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1
  # optional, in MB, default is 1024, min is 128
  memorySize: 128
  # optional, in seconds, default is 6
  timeout: 30
  # optional, default is true
  versionFunctions: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  wsgi:
    app: app.app
    pythonBin: python3 # Some systems with Python3 may require this
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-python-requirements
  - serverless-wsgi
