openapi: 3.0.2
info:
  title: Sustainable Mobility API
  version: 1.0.0
  description:
    Promoting sustainable transportation systems by providing transparency into
    the environmental costs of transport journeys.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: /
paths:
  /estimate-co2:
    summary: Estimate CO2 emissions for a given transportation trip.
    description:
      This endpoint will return an estimation of CO2 (equivalent) impact of a
      given transport trip, provided origin and destination (or pre-calculated
      distance in kilometers), and transportation mode.
    get:
      operationId: api.get_co2_estimate
      responses:
        "200":
          $ref: "#/components/responses/co2_estimate_kg"
      summary: Get an estimate of CO2 emissions for a given transport trip.
      description:
        Provided with origin and destination (or pre-calculated distance in
        kilometers), and transport mode, this endpoint will estimate CO2
        emissions for a given transport trip.
    parameters:
      - examples:
          example_lat:
            value: "60.2055"
        name: origin_lat
        description: Latitude for trip origin (using WGS 84).
        schema:
          format: float
          type: number
        in: query
        required: false
      - examples:
          example_lon:
            value: "24.9384"
        name: origin_lon
        description: Longitude for trip origin (using WGS 84).
        schema:
          format: float
          type: number
        in: query
        required: false
      - examples:
          example_lat:
            value: "60.1699"
        name: destination_lat
        description: Latitude for trip destination (using WGS 84).
        schema:
          format: float
          type: number
        in: query
        required: false
      - examples:
          example_lon:
            value: "24.9384"
        name: destination_lon
        description: Longitude for trip destination (using WGS 84).
        schema:
          format: float
          type: number
        in: query
        required: false
      - examples:
          example_small_car_mode:
            value: SMALL_CAR
        name: transport_mode
        description: Mode of transportation for given trip (leg).
        schema:
          enum:
            - LIGHT_RAIL
            - SMALL_CAR
            - LARGE_CAR
            - SCOOTER
            - BUS
            - WALK
            - BICYCLE
            - CAR
            - TRAM
            - SUBWAY
            - RAIL
            - FERRY
            - CABLE_CAR
            - GONDOLA
            - FUNICULAR
            - TRANSIT
            - LEG_SWITCH
            - AIRPLANE
          type: string
        in: query
        required: true
      - examples:
          vehicle_occupancy_example:
            value: "3"
        name: vehicle_occupancy
        description: Number of anticipated passengers in vehicle at time of trip.
        schema:
          type: integer
        in: query
        required: false
      - name: distance_km
        description: Distance of trip or leg in kilometers.
        schema:
          type: number
        in: query
        required: false
components:
  responses:
    co2_estimate_kg:
      description:
        This contains an estimate of CO2 emissions in grams for the given
        transportation trip.
